# Generated by Django 3.1.1 on 2020-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aCommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='famille',
            field=models.CharField(default='', max_length=21),
            preserve_default=False,
        ),
    ]
