# Generated by Django 3.1.7 on 2021-02-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aCommerce', '0002_produit_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_promo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='produit_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=500),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aCommerce.categorie')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aCommerce.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Figurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aCommerce.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('jour_commande', models.DateTimeField()),
                ('produits', models.ManyToManyField(to='aCommerce.Figurer')),
            ],
        ),
    ]
